### ISSUE TITLE
panics when collecting metrics

### ISSUE THREAD

**Issue by nvloff** [form3tech-oss/extra-cilium-metrics#10]
```
2021/01/25 16:59:02 http: panic serving 10.129.5.123:60680: runtime error: invalid memory address or nil pointer dereference                                                                 
 goroutine 170767 [running]:                                                                                                                                                                  
 net/http.(*conn).serve.func1(0xc00020d900)                                                                                                                                                   
     /usr/local/go/src/net/http/server.go:1801 +0x147                                                                                                                                         
 panic(0xb77520, 0x1143d00)                                                                                                                                                                   
     /usr/local/go/src/runtime/panic.go:975 +0x3e9                                                                                                                                            
 main.collectMetrics(0xc000558280, 0xc000511200, 0x0, 0x0)                                                                                                                                    
     /go/src/github.com/form3tech-oss/extra-cilium-metrics/main.go:267 +0x15e7                                                                                                                
 main.main.func1(0xd21c60, 0xc000144d20, 0xc000561300)                                                                                                                                        
     /go/src/github.com/form3tech-oss/extra-cilium-metrics/main.go:340 +0x37                                                                                                                  
 net/http.HandlerFunc.ServeHTTP(0xc000511240, 0xd21c60, 0xc000144d20, 0xc000561300)                                                                                                           
     /usr/local/go/src/net/http/server.go:2042 +0x44                                                                                                                                          
 net/http.(*ServeMux).ServeHTTP(0x1160580, 0xd21c60, 0xc000144d20, 0xc000561300)                                                                                                              
     /usr/local/go/src/net/http/server.go:2417 +0x1ad                                                                                                                                         
 net/http.serverHandler.ServeHTTP(0xc000578000, 0xd21c60, 0xc000144d20, 0xc000561300)                                                                                                         
     /usr/local/go/src/net/http/server.go:2843 +0xa3                                                                                                                                          
 net/http.(*conn).serve(0xc00020d900, 0xd23aa0, 0xc000526800)                                                                                                                                 
     /usr/local/go/src/net/http/server.go:1925 +0x8ad                                                                                                                                         
 created by net/http.(*Server).Serve                                                                                                                                                          
     /usr/local/go/src/net/http/server.go:2969 +0x36c                     
```

also not good :) 

```
time="2021-01-25T17:09:12Z" level=error msg="Get \"http://%2Fvar%2Frun%2Fcilium%2Fcilium.sock/v1/healthz\": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory"
```

**Comment by bmcustodio** [comment]
Closed via #11.
